version: 0.0
Resources:
 - TargetService:
     Type: AWS::ECS::Service
     Properties:
       TaskDefinition: "arn:aws:ecs:ap-south-1:955344041027:task-definition/microservice-task:1"
       LoadBalancerInfo:
         ContainerName: "microservice"
         ContainerPort: 80
